/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
    pgTable,
    index,
    uniqueIndex,
    foreignKey,
    integer,
    varchar,
    timestamp,
    serial,
    numeric,
    text,
    jsonb,
    boolean,
    pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_forms_blocks_email_width = pgEnum('enum_forms_blocks_email_width', [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
])
export const enum_forms_blocks_text_width = pgEnum('enum_forms_blocks_text_width', [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
])
export const enum_forms_blocks_textarea_width = pgEnum('enum_forms_blocks_textarea_width', [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
])
export const enum_forms_confirmation_type = pgEnum('enum_forms_confirmation_type', [
    'message',
    'redirect',
])

export const users_sessions = pgTable(
    'users_sessions',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        id: varchar('id').primaryKey(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
        expiresAt: timestamp('expires_at', {
            mode: 'string',
            withTimezone: true,
            precision: 3,
        }).notNull(),
    },
    (columns) => [
        index('users_sessions_order_idx').on(columns._order),
        index('users_sessions_parent_id_idx').on(columns._parentID),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [users.id],
            name: 'users_sessions_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const users = pgTable(
    'users',
    {
        id: serial('id').primaryKey(),
        updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        email: varchar('email').notNull(),
        resetPasswordToken: varchar('reset_password_token'),
        resetPasswordExpiration: timestamp('reset_password_expiration', {
            mode: 'string',
            withTimezone: true,
            precision: 3,
        }),
        salt: varchar('salt'),
        hash: varchar('hash'),
        loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
        lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
    },
    (columns) => [
        index('users_updated_at_idx').on(columns.updatedAt),
        index('users_created_at_idx').on(columns.createdAt),
        uniqueIndex('users_email_idx').on(columns.email),
    ],
)

export const media = pgTable(
    'media',
    {
        id: serial('id').primaryKey(),
        alt: varchar('alt').notNull(),
        updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        url: varchar('url'),
        thumbnailURL: varchar('thumbnail_u_r_l'),
        filename: varchar('filename'),
        mimeType: varchar('mime_type'),
        filesize: numeric('filesize', { mode: 'number' }),
        width: numeric('width', { mode: 'number' }),
        height: numeric('height', { mode: 'number' }),
        focalX: numeric('focal_x', { mode: 'number' }),
        focalY: numeric('focal_y', { mode: 'number' }),
        sizes_thumbnail_url: varchar('sizes_thumbnail_url'),
        sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
        sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
        sizes_thumbnail_mimeType: varchar('sizes_thumbnail_mime_type'),
        sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
        sizes_thumbnail_filename: varchar('sizes_thumbnail_filename'),
        sizes_square_url: varchar('sizes_square_url'),
        sizes_square_width: numeric('sizes_square_width', { mode: 'number' }),
        sizes_square_height: numeric('sizes_square_height', { mode: 'number' }),
        sizes_square_mimeType: varchar('sizes_square_mime_type'),
        sizes_square_filesize: numeric('sizes_square_filesize', { mode: 'number' }),
        sizes_square_filename: varchar('sizes_square_filename'),
        sizes_small_url: varchar('sizes_small_url'),
        sizes_small_width: numeric('sizes_small_width', { mode: 'number' }),
        sizes_small_height: numeric('sizes_small_height', { mode: 'number' }),
        sizes_small_mimeType: varchar('sizes_small_mime_type'),
        sizes_small_filesize: numeric('sizes_small_filesize', { mode: 'number' }),
        sizes_small_filename: varchar('sizes_small_filename'),
        sizes_medium_url: varchar('sizes_medium_url'),
        sizes_medium_width: numeric('sizes_medium_width', { mode: 'number' }),
        sizes_medium_height: numeric('sizes_medium_height', { mode: 'number' }),
        sizes_medium_mimeType: varchar('sizes_medium_mime_type'),
        sizes_medium_filesize: numeric('sizes_medium_filesize', { mode: 'number' }),
        sizes_medium_filename: varchar('sizes_medium_filename'),
        sizes_large_url: varchar('sizes_large_url'),
        sizes_large_width: numeric('sizes_large_width', { mode: 'number' }),
        sizes_large_height: numeric('sizes_large_height', { mode: 'number' }),
        sizes_large_mimeType: varchar('sizes_large_mime_type'),
        sizes_large_filesize: numeric('sizes_large_filesize', { mode: 'number' }),
        sizes_large_filename: varchar('sizes_large_filename'),
        sizes_xlarge_url: varchar('sizes_xlarge_url'),
        sizes_xlarge_width: numeric('sizes_xlarge_width', { mode: 'number' }),
        sizes_xlarge_height: numeric('sizes_xlarge_height', { mode: 'number' }),
        sizes_xlarge_mimeType: varchar('sizes_xlarge_mime_type'),
        sizes_xlarge_filesize: numeric('sizes_xlarge_filesize', { mode: 'number' }),
        sizes_xlarge_filename: varchar('sizes_xlarge_filename'),
        sizes_og_url: varchar('sizes_og_url'),
        sizes_og_width: numeric('sizes_og_width', { mode: 'number' }),
        sizes_og_height: numeric('sizes_og_height', { mode: 'number' }),
        sizes_og_mimeType: varchar('sizes_og_mime_type'),
        sizes_og_filesize: numeric('sizes_og_filesize', { mode: 'number' }),
        sizes_og_filename: varchar('sizes_og_filename'),
    },
    (columns) => [
        index('media_updated_at_idx').on(columns.updatedAt),
        index('media_created_at_idx').on(columns.createdAt),
        uniqueIndex('media_filename_idx').on(columns.filename),
        index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
            columns.sizes_thumbnail_filename,
        ),
        index('media_sizes_square_sizes_square_filename_idx').on(columns.sizes_square_filename),
        index('media_sizes_small_sizes_small_filename_idx').on(columns.sizes_small_filename),
        index('media_sizes_medium_sizes_medium_filename_idx').on(columns.sizes_medium_filename),
        index('media_sizes_large_sizes_large_filename_idx').on(columns.sizes_large_filename),
        index('media_sizes_xlarge_sizes_xlarge_filename_idx').on(columns.sizes_xlarge_filename),
        index('media_sizes_og_sizes_og_filename_idx').on(columns.sizes_og_filename),
    ],
)

export const pages_blocks_hero = pgTable(
    'pages_blocks_hero',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        title: varchar('title').notNull(),
        text: jsonb('text').notNull(),
        image1: integer('image1_id')
            .notNull()
            .references(() => media.id, {
                onDelete: 'set null',
            }),
        image2: integer('image2_id')
            .notNull()
            .references(() => media.id, {
                onDelete: 'set null',
            }),
        image3: integer('image3_id')
            .notNull()
            .references(() => media.id, {
                onDelete: 'set null',
            }),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('pages_blocks_hero_order_idx').on(columns._order),
        index('pages_blocks_hero_parent_id_idx').on(columns._parentID),
        index('pages_blocks_hero_path_idx').on(columns._path),
        index('pages_blocks_hero_image1_idx').on(columns.image1),
        index('pages_blocks_hero_image2_idx').on(columns.image2),
        index('pages_blocks_hero_image3_idx').on(columns.image3),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [pages.id],
            name: 'pages_blocks_hero_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const pages_blocks_gallery_images = pgTable(
    'pages_blocks_gallery_images',
    {
        _order: integer('_order').notNull(),
        _parentID: varchar('_parent_id').notNull(),
        id: varchar('id').primaryKey(),
        image: integer('image_id')
            .notNull()
            .references(() => media.id, {
                onDelete: 'set null',
            }),
    },
    (columns) => [
        index('pages_blocks_gallery_images_order_idx').on(columns._order),
        index('pages_blocks_gallery_images_parent_id_idx').on(columns._parentID),
        index('pages_blocks_gallery_images_image_idx').on(columns.image),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [pages_blocks_gallery.id],
            name: 'pages_blocks_gallery_images_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const pages_blocks_gallery = pgTable(
    'pages_blocks_gallery',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        highlight: varchar('highlight').notNull(),
        title: varchar('title').notNull(),
        text: jsonb('text').notNull(),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('pages_blocks_gallery_order_idx').on(columns._order),
        index('pages_blocks_gallery_parent_id_idx').on(columns._parentID),
        index('pages_blocks_gallery_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [pages.id],
            name: 'pages_blocks_gallery_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const pages_blocks_testimonial = pgTable(
    'pages_blocks_testimonial',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        text: jsonb('text').notNull(),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('pages_blocks_testimonial_order_idx').on(columns._order),
        index('pages_blocks_testimonial_parent_id_idx').on(columns._parentID),
        index('pages_blocks_testimonial_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [pages.id],
            name: 'pages_blocks_testimonial_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const pages_blocks_cta = pgTable(
    'pages_blocks_cta',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        highlight: varchar('highlight').notNull(),
        title: varchar('title').notNull(),
        text: jsonb('text').notNull(),
        image: integer('image_id')
            .notNull()
            .references(() => media.id, {
                onDelete: 'set null',
            }),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('pages_blocks_cta_order_idx').on(columns._order),
        index('pages_blocks_cta_parent_id_idx').on(columns._parentID),
        index('pages_blocks_cta_path_idx').on(columns._path),
        index('pages_blocks_cta_image_idx').on(columns.image),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [pages.id],
            name: 'pages_blocks_cta_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const pages_blocks_form = pgTable(
    'pages_blocks_form',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        highlight: varchar('highlight').notNull(),
        title: varchar('title').notNull(),
        text: jsonb('text').notNull(),
        form: integer('form_id')
            .notNull()
            .references(() => forms.id, {
                onDelete: 'set null',
            }),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('pages_blocks_form_order_idx').on(columns._order),
        index('pages_blocks_form_parent_id_idx').on(columns._parentID),
        index('pages_blocks_form_path_idx').on(columns._path),
        index('pages_blocks_form_form_idx').on(columns.form),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [pages.id],
            name: 'pages_blocks_form_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const pages = pgTable(
    'pages',
    {
        id: serial('id').primaryKey(),
        meta_title: varchar('meta_title'),
        meta_description: varchar('meta_description'),
        title: varchar('title').notNull(),
        generateSlug: boolean('generate_slug').default(true),
        slug: varchar('slug').notNull(),
        updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
    },
    (columns) => [
        uniqueIndex('pages_slug_idx').on(columns.slug),
        index('pages_updated_at_idx').on(columns.updatedAt),
        index('pages_created_at_idx').on(columns.createdAt),
    ],
)

export const forms_blocks_checkbox = pgTable(
    'forms_blocks_checkbox',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        label: varchar('label'),
        width: numeric('width', { mode: 'number' }),
        required: boolean('required'),
        defaultValue: boolean('default_value'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_checkbox_order_idx').on(columns._order),
        index('forms_blocks_checkbox_parent_id_idx').on(columns._parentID),
        index('forms_blocks_checkbox_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_checkbox_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_country = pgTable(
    'forms_blocks_country',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        label: varchar('label'),
        width: numeric('width', { mode: 'number' }),
        required: boolean('required'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_country_order_idx').on(columns._order),
        index('forms_blocks_country_parent_id_idx').on(columns._parentID),
        index('forms_blocks_country_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_country_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_email = pgTable(
    'forms_blocks_email',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        label: varchar('label'),
        placeholder: varchar('placeholder'),
        width: enum_forms_blocks_email_width('width').notNull(),
        required: boolean('required'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_email_order_idx').on(columns._order),
        index('forms_blocks_email_parent_id_idx').on(columns._parentID),
        index('forms_blocks_email_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_email_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_message = pgTable(
    'forms_blocks_message',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        message: jsonb('message'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_message_order_idx').on(columns._order),
        index('forms_blocks_message_parent_id_idx').on(columns._parentID),
        index('forms_blocks_message_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_message_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_number = pgTable(
    'forms_blocks_number',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        label: varchar('label'),
        width: numeric('width', { mode: 'number' }),
        defaultValue: numeric('default_value', { mode: 'number' }),
        required: boolean('required'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_number_order_idx').on(columns._order),
        index('forms_blocks_number_parent_id_idx').on(columns._parentID),
        index('forms_blocks_number_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_number_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_select_options = pgTable(
    'forms_blocks_select_options',
    {
        _order: integer('_order').notNull(),
        _parentID: varchar('_parent_id').notNull(),
        id: varchar('id').primaryKey(),
        label: varchar('label').notNull(),
        value: varchar('value').notNull(),
    },
    (columns) => [
        index('forms_blocks_select_options_order_idx').on(columns._order),
        index('forms_blocks_select_options_parent_id_idx').on(columns._parentID),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms_blocks_select.id],
            name: 'forms_blocks_select_options_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_select = pgTable(
    'forms_blocks_select',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        label: varchar('label'),
        width: numeric('width', { mode: 'number' }),
        defaultValue: varchar('default_value'),
        placeholder: varchar('placeholder'),
        required: boolean('required'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_select_order_idx').on(columns._order),
        index('forms_blocks_select_parent_id_idx').on(columns._parentID),
        index('forms_blocks_select_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_select_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_state = pgTable(
    'forms_blocks_state',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        label: varchar('label'),
        width: numeric('width', { mode: 'number' }),
        required: boolean('required'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_state_order_idx').on(columns._order),
        index('forms_blocks_state_parent_id_idx').on(columns._parentID),
        index('forms_blocks_state_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_state_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_text = pgTable(
    'forms_blocks_text',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        label: varchar('label'),
        placeholder: varchar('placeholder'),
        width: enum_forms_blocks_text_width('width').notNull(),
        required: boolean('required'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_text_order_idx').on(columns._order),
        index('forms_blocks_text_parent_id_idx').on(columns._parentID),
        index('forms_blocks_text_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_text_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_blocks_textarea = pgTable(
    'forms_blocks_textarea',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        _path: text('_path').notNull(),
        id: varchar('id').primaryKey(),
        name: varchar('name').notNull(),
        label: varchar('label'),
        placeholder: varchar('placeholder'),
        width: enum_forms_blocks_textarea_width('width').notNull(),
        required: boolean('required'),
        blockName: varchar('block_name'),
    },
    (columns) => [
        index('forms_blocks_textarea_order_idx').on(columns._order),
        index('forms_blocks_textarea_parent_id_idx').on(columns._parentID),
        index('forms_blocks_textarea_path_idx').on(columns._path),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_blocks_textarea_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms_emails = pgTable(
    'forms_emails',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        id: varchar('id').primaryKey(),
        emailTo: varchar('email_to'),
        cc: varchar('cc'),
        bcc: varchar('bcc'),
        replyTo: varchar('reply_to'),
        emailFrom: varchar('email_from'),
        subject: varchar('subject').notNull().default("You've received a new message."),
        message: jsonb('message'),
    },
    (columns) => [
        index('forms_emails_order_idx').on(columns._order),
        index('forms_emails_parent_id_idx').on(columns._parentID),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [forms.id],
            name: 'forms_emails_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const forms = pgTable(
    'forms',
    {
        id: serial('id').primaryKey(),
        title: varchar('title').notNull(),
        submitButtonLabel: varchar('submit_button_label'),
        confirmationType: enum_forms_confirmation_type('confirmation_type').default('message'),
        confirmationMessage: jsonb('confirmation_message'),
        redirect_url: varchar('redirect_url'),
        updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
    },
    (columns) => [
        index('forms_updated_at_idx').on(columns.updatedAt),
        index('forms_created_at_idx').on(columns.createdAt),
    ],
)

export const form_submissions_submission_data = pgTable(
    'form_submissions_submission_data',
    {
        _order: integer('_order').notNull(),
        _parentID: integer('_parent_id').notNull(),
        id: varchar('id').primaryKey(),
        field: varchar('field').notNull(),
        value: varchar('value').notNull(),
    },
    (columns) => [
        index('form_submissions_submission_data_order_idx').on(columns._order),
        index('form_submissions_submission_data_parent_id_idx').on(columns._parentID),
        foreignKey({
            columns: [columns['_parentID']],
            foreignColumns: [form_submissions.id],
            name: 'form_submissions_submission_data_parent_id_fk',
        }).onDelete('cascade'),
    ],
)

export const form_submissions = pgTable(
    'form_submissions',
    {
        id: serial('id').primaryKey(),
        form: integer('form_id')
            .notNull()
            .references(() => forms.id, {
                onDelete: 'set null',
            }),
        updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
    },
    (columns) => [
        index('form_submissions_form_idx').on(columns.form),
        index('form_submissions_updated_at_idx').on(columns.updatedAt),
        index('form_submissions_created_at_idx').on(columns.createdAt),
    ],
)

export const payload_kv = pgTable(
    'payload_kv',
    {
        id: serial('id').primaryKey(),
        key: varchar('key').notNull(),
        data: jsonb('data').notNull(),
    },
    (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
    'payload_locked_documents',
    {
        id: serial('id').primaryKey(),
        globalSlug: varchar('global_slug'),
        updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
    },
    (columns) => [
        index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
        index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
        index('payload_locked_documents_created_at_idx').on(columns.createdAt),
    ],
)

export const payload_locked_documents_rels = pgTable(
    'payload_locked_documents_rels',
    {
        id: serial('id').primaryKey(),
        order: integer('order'),
        parent: integer('parent_id').notNull(),
        path: varchar('path').notNull(),
        usersID: integer('users_id'),
        mediaID: integer('media_id'),
        pagesID: integer('pages_id'),
        formsID: integer('forms_id'),
        'form-submissionsID': integer('form_submissions_id'),
    },
    (columns) => [
        index('payload_locked_documents_rels_order_idx').on(columns.order),
        index('payload_locked_documents_rels_parent_idx').on(columns.parent),
        index('payload_locked_documents_rels_path_idx').on(columns.path),
        index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
        index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
        index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
        index('payload_locked_documents_rels_forms_id_idx').on(columns.formsID),
        index('payload_locked_documents_rels_form_submissions_id_idx').on(
            columns['form-submissionsID'],
        ),
        foreignKey({
            columns: [columns['parent']],
            foreignColumns: [payload_locked_documents.id],
            name: 'payload_locked_documents_rels_parent_fk',
        }).onDelete('cascade'),
        foreignKey({
            columns: [columns['usersID']],
            foreignColumns: [users.id],
            name: 'payload_locked_documents_rels_users_fk',
        }).onDelete('cascade'),
        foreignKey({
            columns: [columns['mediaID']],
            foreignColumns: [media.id],
            name: 'payload_locked_documents_rels_media_fk',
        }).onDelete('cascade'),
        foreignKey({
            columns: [columns['pagesID']],
            foreignColumns: [pages.id],
            name: 'payload_locked_documents_rels_pages_fk',
        }).onDelete('cascade'),
        foreignKey({
            columns: [columns['formsID']],
            foreignColumns: [forms.id],
            name: 'payload_locked_documents_rels_forms_fk',
        }).onDelete('cascade'),
        foreignKey({
            columns: [columns['form-submissionsID']],
            foreignColumns: [form_submissions.id],
            name: 'payload_locked_documents_rels_form_submissions_fk',
        }).onDelete('cascade'),
    ],
)

export const payload_preferences = pgTable(
    'payload_preferences',
    {
        id: serial('id').primaryKey(),
        key: varchar('key'),
        value: jsonb('value'),
        updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
    },
    (columns) => [
        index('payload_preferences_key_idx').on(columns.key),
        index('payload_preferences_updated_at_idx').on(columns.updatedAt),
        index('payload_preferences_created_at_idx').on(columns.createdAt),
    ],
)

export const payload_preferences_rels = pgTable(
    'payload_preferences_rels',
    {
        id: serial('id').primaryKey(),
        order: integer('order'),
        parent: integer('parent_id').notNull(),
        path: varchar('path').notNull(),
        usersID: integer('users_id'),
    },
    (columns) => [
        index('payload_preferences_rels_order_idx').on(columns.order),
        index('payload_preferences_rels_parent_idx').on(columns.parent),
        index('payload_preferences_rels_path_idx').on(columns.path),
        index('payload_preferences_rels_users_id_idx').on(columns.usersID),
        foreignKey({
            columns: [columns['parent']],
            foreignColumns: [payload_preferences.id],
            name: 'payload_preferences_rels_parent_fk',
        }).onDelete('cascade'),
        foreignKey({
            columns: [columns['usersID']],
            foreignColumns: [users.id],
            name: 'payload_preferences_rels_users_fk',
        }).onDelete('cascade'),
    ],
)

export const payload_migrations = pgTable(
    'payload_migrations',
    {
        id: serial('id').primaryKey(),
        name: varchar('name'),
        batch: numeric('batch', { mode: 'number' }),
        updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
        createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
            .defaultNow()
            .notNull(),
    },
    (columns) => [
        index('payload_migrations_updated_at_idx').on(columns.updatedAt),
        index('payload_migrations_created_at_idx').on(columns.createdAt),
    ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
    _parentID: one(users, {
        fields: [users_sessions._parentID],
        references: [users.id],
        relationName: 'sessions',
    }),
}))
export const relations_users = relations(users, ({ many }) => ({
    sessions: many(users_sessions, {
        relationName: 'sessions',
    }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_pages_blocks_hero = relations(pages_blocks_hero, ({ one }) => ({
    _parentID: one(pages, {
        fields: [pages_blocks_hero._parentID],
        references: [pages.id],
        relationName: '_blocks_hero',
    }),
    image1: one(media, {
        fields: [pages_blocks_hero.image1],
        references: [media.id],
        relationName: 'image1',
    }),
    image2: one(media, {
        fields: [pages_blocks_hero.image2],
        references: [media.id],
        relationName: 'image2',
    }),
    image3: one(media, {
        fields: [pages_blocks_hero.image3],
        references: [media.id],
        relationName: 'image3',
    }),
}))
export const relations_pages_blocks_gallery_images = relations(
    pages_blocks_gallery_images,
    ({ one }) => ({
        _parentID: one(pages_blocks_gallery, {
            fields: [pages_blocks_gallery_images._parentID],
            references: [pages_blocks_gallery.id],
            relationName: 'images',
        }),
        image: one(media, {
            fields: [pages_blocks_gallery_images.image],
            references: [media.id],
            relationName: 'image',
        }),
    }),
)
export const relations_pages_blocks_gallery = relations(pages_blocks_gallery, ({ one, many }) => ({
    _parentID: one(pages, {
        fields: [pages_blocks_gallery._parentID],
        references: [pages.id],
        relationName: '_blocks_gallery',
    }),
    images: many(pages_blocks_gallery_images, {
        relationName: 'images',
    }),
}))
export const relations_pages_blocks_testimonial = relations(
    pages_blocks_testimonial,
    ({ one }) => ({
        _parentID: one(pages, {
            fields: [pages_blocks_testimonial._parentID],
            references: [pages.id],
            relationName: '_blocks_testimonial',
        }),
    }),
)
export const relations_pages_blocks_cta = relations(pages_blocks_cta, ({ one }) => ({
    _parentID: one(pages, {
        fields: [pages_blocks_cta._parentID],
        references: [pages.id],
        relationName: '_blocks_cta',
    }),
    image: one(media, {
        fields: [pages_blocks_cta.image],
        references: [media.id],
        relationName: 'image',
    }),
}))
export const relations_pages_blocks_form = relations(pages_blocks_form, ({ one }) => ({
    _parentID: one(pages, {
        fields: [pages_blocks_form._parentID],
        references: [pages.id],
        relationName: '_blocks_form',
    }),
    form: one(forms, {
        fields: [pages_blocks_form.form],
        references: [forms.id],
        relationName: 'form',
    }),
}))
export const relations_pages = relations(pages, ({ many }) => ({
    _blocks_hero: many(pages_blocks_hero, {
        relationName: '_blocks_hero',
    }),
    _blocks_gallery: many(pages_blocks_gallery, {
        relationName: '_blocks_gallery',
    }),
    _blocks_testimonial: many(pages_blocks_testimonial, {
        relationName: '_blocks_testimonial',
    }),
    _blocks_cta: many(pages_blocks_cta, {
        relationName: '_blocks_cta',
    }),
    _blocks_form: many(pages_blocks_form, {
        relationName: '_blocks_form',
    }),
}))
export const relations_forms_blocks_checkbox = relations(forms_blocks_checkbox, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_checkbox._parentID],
        references: [forms.id],
        relationName: '_blocks_checkbox',
    }),
}))
export const relations_forms_blocks_country = relations(forms_blocks_country, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_country._parentID],
        references: [forms.id],
        relationName: '_blocks_country',
    }),
}))
export const relations_forms_blocks_email = relations(forms_blocks_email, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_email._parentID],
        references: [forms.id],
        relationName: '_blocks_email',
    }),
}))
export const relations_forms_blocks_message = relations(forms_blocks_message, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_message._parentID],
        references: [forms.id],
        relationName: '_blocks_message',
    }),
}))
export const relations_forms_blocks_number = relations(forms_blocks_number, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_number._parentID],
        references: [forms.id],
        relationName: '_blocks_number',
    }),
}))
export const relations_forms_blocks_select_options = relations(
    forms_blocks_select_options,
    ({ one }) => ({
        _parentID: one(forms_blocks_select, {
            fields: [forms_blocks_select_options._parentID],
            references: [forms_blocks_select.id],
            relationName: 'options',
        }),
    }),
)
export const relations_forms_blocks_select = relations(forms_blocks_select, ({ one, many }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_select._parentID],
        references: [forms.id],
        relationName: '_blocks_select',
    }),
    options: many(forms_blocks_select_options, {
        relationName: 'options',
    }),
}))
export const relations_forms_blocks_state = relations(forms_blocks_state, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_state._parentID],
        references: [forms.id],
        relationName: '_blocks_state',
    }),
}))
export const relations_forms_blocks_text = relations(forms_blocks_text, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_text._parentID],
        references: [forms.id],
        relationName: '_blocks_text',
    }),
}))
export const relations_forms_blocks_textarea = relations(forms_blocks_textarea, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_blocks_textarea._parentID],
        references: [forms.id],
        relationName: '_blocks_textarea',
    }),
}))
export const relations_forms_emails = relations(forms_emails, ({ one }) => ({
    _parentID: one(forms, {
        fields: [forms_emails._parentID],
        references: [forms.id],
        relationName: 'emails',
    }),
}))
export const relations_forms = relations(forms, ({ many }) => ({
    _blocks_checkbox: many(forms_blocks_checkbox, {
        relationName: '_blocks_checkbox',
    }),
    _blocks_country: many(forms_blocks_country, {
        relationName: '_blocks_country',
    }),
    _blocks_email: many(forms_blocks_email, {
        relationName: '_blocks_email',
    }),
    _blocks_message: many(forms_blocks_message, {
        relationName: '_blocks_message',
    }),
    _blocks_number: many(forms_blocks_number, {
        relationName: '_blocks_number',
    }),
    _blocks_select: many(forms_blocks_select, {
        relationName: '_blocks_select',
    }),
    _blocks_state: many(forms_blocks_state, {
        relationName: '_blocks_state',
    }),
    _blocks_text: many(forms_blocks_text, {
        relationName: '_blocks_text',
    }),
    _blocks_textarea: many(forms_blocks_textarea, {
        relationName: '_blocks_textarea',
    }),
    emails: many(forms_emails, {
        relationName: 'emails',
    }),
}))
export const relations_form_submissions_submission_data = relations(
    form_submissions_submission_data,
    ({ one }) => ({
        _parentID: one(form_submissions, {
            fields: [form_submissions_submission_data._parentID],
            references: [form_submissions.id],
            relationName: 'submissionData',
        }),
    }),
)
export const relations_form_submissions = relations(form_submissions, ({ one, many }) => ({
    form: one(forms, {
        fields: [form_submissions.form],
        references: [forms.id],
        relationName: 'form',
    }),
    submissionData: many(form_submissions_submission_data, {
        relationName: 'submissionData',
    }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
    payload_locked_documents_rels,
    ({ one }) => ({
        parent: one(payload_locked_documents, {
            fields: [payload_locked_documents_rels.parent],
            references: [payload_locked_documents.id],
            relationName: '_rels',
        }),
        usersID: one(users, {
            fields: [payload_locked_documents_rels.usersID],
            references: [users.id],
            relationName: 'users',
        }),
        mediaID: one(media, {
            fields: [payload_locked_documents_rels.mediaID],
            references: [media.id],
            relationName: 'media',
        }),
        pagesID: one(pages, {
            fields: [payload_locked_documents_rels.pagesID],
            references: [pages.id],
            relationName: 'pages',
        }),
        formsID: one(forms, {
            fields: [payload_locked_documents_rels.formsID],
            references: [forms.id],
            relationName: 'forms',
        }),
        'form-submissionsID': one(form_submissions, {
            fields: [payload_locked_documents_rels['form-submissionsID']],
            references: [form_submissions.id],
            relationName: 'form-submissions',
        }),
    }),
)
export const relations_payload_locked_documents = relations(
    payload_locked_documents,
    ({ many }) => ({
        _rels: many(payload_locked_documents_rels, {
            relationName: '_rels',
        }),
    }),
)
export const relations_payload_preferences_rels = relations(
    payload_preferences_rels,
    ({ one }) => ({
        parent: one(payload_preferences, {
            fields: [payload_preferences_rels.parent],
            references: [payload_preferences.id],
            relationName: '_rels',
        }),
        usersID: one(users, {
            fields: [payload_preferences_rels.usersID],
            references: [users.id],
            relationName: 'users',
        }),
    }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
    _rels: many(payload_preferences_rels, {
        relationName: '_rels',
    }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
    enum_forms_blocks_email_width: typeof enum_forms_blocks_email_width
    enum_forms_blocks_text_width: typeof enum_forms_blocks_text_width
    enum_forms_blocks_textarea_width: typeof enum_forms_blocks_textarea_width
    enum_forms_confirmation_type: typeof enum_forms_confirmation_type
    users_sessions: typeof users_sessions
    users: typeof users
    media: typeof media
    pages_blocks_hero: typeof pages_blocks_hero
    pages_blocks_gallery_images: typeof pages_blocks_gallery_images
    pages_blocks_gallery: typeof pages_blocks_gallery
    pages_blocks_testimonial: typeof pages_blocks_testimonial
    pages_blocks_cta: typeof pages_blocks_cta
    pages_blocks_form: typeof pages_blocks_form
    pages: typeof pages
    forms_blocks_checkbox: typeof forms_blocks_checkbox
    forms_blocks_country: typeof forms_blocks_country
    forms_blocks_email: typeof forms_blocks_email
    forms_blocks_message: typeof forms_blocks_message
    forms_blocks_number: typeof forms_blocks_number
    forms_blocks_select_options: typeof forms_blocks_select_options
    forms_blocks_select: typeof forms_blocks_select
    forms_blocks_state: typeof forms_blocks_state
    forms_blocks_text: typeof forms_blocks_text
    forms_blocks_textarea: typeof forms_blocks_textarea
    forms_emails: typeof forms_emails
    forms: typeof forms
    form_submissions_submission_data: typeof form_submissions_submission_data
    form_submissions: typeof form_submissions
    payload_kv: typeof payload_kv
    payload_locked_documents: typeof payload_locked_documents
    payload_locked_documents_rels: typeof payload_locked_documents_rels
    payload_preferences: typeof payload_preferences
    payload_preferences_rels: typeof payload_preferences_rels
    payload_migrations: typeof payload_migrations
    relations_users_sessions: typeof relations_users_sessions
    relations_users: typeof relations_users
    relations_media: typeof relations_media
    relations_pages_blocks_hero: typeof relations_pages_blocks_hero
    relations_pages_blocks_gallery_images: typeof relations_pages_blocks_gallery_images
    relations_pages_blocks_gallery: typeof relations_pages_blocks_gallery
    relations_pages_blocks_testimonial: typeof relations_pages_blocks_testimonial
    relations_pages_blocks_cta: typeof relations_pages_blocks_cta
    relations_pages_blocks_form: typeof relations_pages_blocks_form
    relations_pages: typeof relations_pages
    relations_forms_blocks_checkbox: typeof relations_forms_blocks_checkbox
    relations_forms_blocks_country: typeof relations_forms_blocks_country
    relations_forms_blocks_email: typeof relations_forms_blocks_email
    relations_forms_blocks_message: typeof relations_forms_blocks_message
    relations_forms_blocks_number: typeof relations_forms_blocks_number
    relations_forms_blocks_select_options: typeof relations_forms_blocks_select_options
    relations_forms_blocks_select: typeof relations_forms_blocks_select
    relations_forms_blocks_state: typeof relations_forms_blocks_state
    relations_forms_blocks_text: typeof relations_forms_blocks_text
    relations_forms_blocks_textarea: typeof relations_forms_blocks_textarea
    relations_forms_emails: typeof relations_forms_emails
    relations_forms: typeof relations_forms
    relations_form_submissions_submission_data: typeof relations_form_submissions_submission_data
    relations_form_submissions: typeof relations_form_submissions
    relations_payload_kv: typeof relations_payload_kv
    relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
    relations_payload_locked_documents: typeof relations_payload_locked_documents
    relations_payload_preferences_rels: typeof relations_payload_preferences_rels
    relations_payload_preferences: typeof relations_payload_preferences
    relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
    export interface GeneratedDatabaseSchema {
        schema: DatabaseSchema
    }
}
